// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/auth/logout": {
    params: {};
  };
  "/api/auth/logout/callback": {
    params: {};
  };
  "/logout/success": {
    params: {};
  };
  "/api/userinfo": {
    params: {};
  };
  "/logout/error": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/auth/error": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/auth/logout" | "/api/auth/logout/callback" | "/logout/success" | "/api/userinfo" | "/logout/error" | "/api/auth/*" | "/auth/error" | "/auth/login" | "/profile" | "/*";
  };
  "routes/api.auth.logout.ts": {
    id: "routes/api.auth.logout";
    page: "/api/auth/logout" | "/api/auth/logout/callback";
  };
  "routes/api.auth.logout.callback.ts": {
    id: "routes/api.auth.logout.callback";
    page: "/api/auth/logout/callback";
  };
  "routes/logout.success.tsx": {
    id: "routes/logout.success";
    page: "/logout/success";
  };
  "routes/api.userinfo.tsx": {
    id: "routes/api.userinfo";
    page: "/api/userinfo";
  };
  "routes/logout.error.tsx": {
    id: "routes/logout.error";
    page: "/logout/error";
  };
  "routes/api.auth.$.ts": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
  "routes/auth.error.tsx": {
    id: "routes/auth.error";
    page: "/auth/error";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.auth.logout": typeof import("./app/routes/api.auth.logout.ts");
  "routes/api.auth.logout.callback": typeof import("./app/routes/api.auth.logout.callback.ts");
  "routes/logout.success": typeof import("./app/routes/logout.success.tsx");
  "routes/api.userinfo": typeof import("./app/routes/api.userinfo.tsx");
  "routes/logout.error": typeof import("./app/routes/logout.error.tsx");
  "routes/api.auth.$": typeof import("./app/routes/api.auth.$.ts");
  "routes/auth.error": typeof import("./app/routes/auth.error.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};